const CLOSE_CHECKOUT = "CLOSE_CHECKOUT";
const OPEN_CHECKOUT = "OPEN_CHECKOUT";
const LOAD_DATA = "LOAD_DATA";
const TOGGLE_AMOUNT = "TOGGLE_AMOUNT";
const ADD_TO_CART = "ADD_TO_CART";
const REMOVE_CART = "REMOVE_CART";
const UPDATE_CART_AMOUNT = "UPDATE_CART_AMOUNT";
const GET_CART_TOTALS = "GET_CART_TOTALS";

export {
  OPEN_CHECKOUT,
  CLOSE_CHECKOUT,
  LOAD_DATA,
  TOGGLE_AMOUNT,
  ADD_TO_CART,
  REMOVE_CART,
  UPDATE_CART_AMOUNT,
  GET_CART_TOTALS,
};
